### Tutorial from FreeCodeCamp.org channel: https://www.youtube.com/watch?v=QUT1VHiLmmI

NumPy is a multidimensional library commonly used as a basis or various Scientific computing packages.
NumPy is inherently faster than lists or conventional arrays. This is because NumPy uses fixed type data type, which requires reading through less bytes of memory, no type checking of objects, use of contiguous memory (ie- items not scattered in memory, which would require pointers. This results in benefits of SMID vector processing and effective cache utilization).

In [1]:
#example of list vs NumPy ie- itemwise computation

#lists:
b=[2,3,4]
c=[4,5,6]
d=[]
for i in range (len(b)):
    d.append(b[i]*c[i])

print(d)

[8, 15, 24]


In [2]:
    
#NumPy:
import numpy as np
b=np.array([2,3,4])
c=np.array([4,5,6])
d=b*c
print(d)

[ 8 15 24]


# applications of NumPy

-Mathematics (matlab replacement)  
-plotting (matplotlib)  
-used in backend of various applications (eg- Pandas, Connect 4, Digital Photography ie- storing images)  
-machine learning (eg- tensors)


## Basics

In [3]:
#intialize 1-D array:
a=np.array([2,3,4])
print(a)

[2 3 4]


In [4]:
# 2-D array
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# get dimension
a.ndim

1

In [6]:
#get shape (number of rows and columns)
a.shape

(3,)

In [7]:
b.ndim

2

In [8]:
b.shape

(2, 3)

In [9]:
#get type
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('float64')

In [11]:
#get size
a.itemsize

4

In [12]:
#total number of elements
a.size

3

In [13]:
# total size
a.size*a.itemsize

12

In [14]:
# we can also get total size via number of bytes:
a.nbytes

12

In [15]:
b.itemsize

8

In [16]:
# we can specify our data type, to ensure efficient use of resources:
d=np.array([4,5,6], dtype='int16')
d.dtype

dtype('int16')

## Accessing/Changing specific elemnts, rows, columns, etc

In [17]:
b=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
b.shape

(2, 7)

In [19]:
#get a specific element [row,column]
b[1,5]   #second row, 6th column ,ie-13

13

In [20]:
#or we can use negative index
b[1,-2]

13

In [21]:
# get a specific row
b[0,:]  #use slicing, similar to lists

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
#get specific column
b[:,2]

array([ 3, 10])

In [23]:
#getting a little more fancy ie- [start index: endindex: stepsize]
b[0, 1:-1:2]

array([2, 4, 6])

In [24]:
#changing elements by index
b[1,5]=20
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [25]:
#change entire column (3rd column)
b[:,2]=5
print(b)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [26]:
#to change into specific numbers/sequence, simply supply numbers in same shape as selected range/subsequence
b[:,2]=[1,2]
print(b)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3D example

In [27]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
c.shape

(2, 2, 2)

In [29]:
c.ndim

3

In [30]:
#get specific element (best to work outside-in, when identifying indices bluh bluh)
c[0,1,1]

4

In [31]:
#we can also slice through the elements
c[:,1,:]

array([[3, 4],
       [7, 8]])

In [32]:
#replace elements (recall: shape should be same)
c[:,1,:]=[[9,9],[8,8]]
print(c)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of arrays

In [33]:
#all zero's matrix
#simply use the np.zeros function, passing the parameter of the required shape
np.zeros(5)  #1D

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((2,3))   #2D

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((2,3,3))   #3D

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [36]:
np.zeros((2,3,3,2))  #4D

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [37]:
#all ones matrix
np.ones(5)

array([1., 1., 1., 1., 1.])

In [38]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [39]:
#array full of numbers that aren't 0 or 1
np.full((5),2)

array([2, 2, 2, 2, 2])

In [40]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [41]:
#we can also use shape of defined arrays to initialize array full of a given number using 2 methods

#1-full method
np.full(b.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [42]:
#2-full_like method
np.full_like(b,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

### Generate matrix of random decimal numbers

In [43]:

np.random.rand(4,2)  #note that shape is passed directly to the method without parentheses

array([[0.54503255, 0.00612513],
       [0.89099153, 0.89569529],
       [0.29447946, 0.99242411],
       [0.40304553, 0.20246965]])

In [44]:
np.random.rand(4,2,3)

array([[[0.23651023, 0.49577298, 0.47862022],
        [0.22349414, 0.51320527, 0.10019897]],

       [[0.87984374, 0.3161193 , 0.22719588],
        [0.22406347, 0.62271142, 0.4627868 ]],

       [[0.93401828, 0.61931347, 0.181126  ],
        [0.60425294, 0.80805136, 0.80804062]],

       [[0.15487147, 0.09881292, 0.13371071],
        [0.99519452, 0.0371043 , 0.9162544 ]]])

In [45]:
#use pre-existing shape
np.random.random_sample(a.shape)

array([0.92491016, 0.32469963, 0.50011989])

In [46]:
np.random.random_sample(b.shape)

array([[0.5903206 , 0.13834959, 0.92953119, 0.61560951, 0.08153167,
        0.10876436, 0.86315762],
       [0.56869942, 0.80510315, 0.11004921, 0.09424115, 0.19883025,
        0.11670275, 0.26137068]])

### Generate random integer values

In [47]:
np.random.randint(7)  #random integer between 0-6 (7 is exclusive)

5

In [48]:
np.random.randint(7,size=(3,3))

array([[3, 1, 6],
       [2, 0, 0],
       [1, 0, 4]])

In [49]:
np.random.randint(4,7,size=(3,3))  #3 by 3 array with integers between 4-6

array([[6, 4, 5],
       [6, 6, 5],
       [4, 5, 4]])

### Identity matrix

In [50]:
np.identity(5)   #the only prameter is the dimension of the matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Repeat an array

In [51]:
arr=np.array([1,2,3])
r1=np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [52]:
r1=np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [53]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [54]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [55]:
#simple example
cells=np.ones((5,5),dtype='int32')
print(cells)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [56]:
#slice thru-[start index: endindex: stepsize]
cells[1:4,1:4]=[[0,0,0],[0,9,0],[0,0,0]]
cells

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### Copying arrays!!

In [57]:
d=np.array([2,3,4])
e=d
print(e)

[2 3 4]


In [58]:
e[0]=33
e

array([33,  3,  4])

In [59]:
d

array([33,  3,  4])

In [60]:
#however, we can use the numpy copy function to ensure original array is not changed
d=np.array([3,4,5])
e=d.copy()
e[0]=33
d

array([3, 4, 5])

### Example of numpy in Mathematics

In [61]:
#elementwise computation
b=np.array([2,3,4,5])
print(b)

[2 3 4 5]


In [62]:
b+2

array([4, 5, 6, 7])

In [63]:
b-2

array([0, 1, 2, 3])

In [64]:
b*2

array([ 4,  6,  8, 10])

In [65]:
b/2

array([1. , 1.5, 2. , 2.5])

In [66]:
c=np.array([6,7,8,9])
b+c

array([ 8, 10, 12, 14])

In [67]:
b**2

array([ 4,  9, 16, 25], dtype=int32)

In [68]:
b+=2
print(b)

[4 5 6 7]


In [69]:
np.cos(b)

array([-0.65364362,  0.28366219,  0.96017029,  0.75390225])

### Linear algebra

In [70]:
#multiplying matrices
b=np.ones((2,3))
print(b)

c=np.full((3,2), 2)
print(c)

np.matmul(b,c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [71]:
np.matmul(c,b)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [72]:
#determinant
c=np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [73]:
stats=np.random.rand(2,3)
stats

array([[0.09166967, 0.38406215, 0.539444  ],
       [0.14981479, 0.79928805, 0.39098961]])

In [74]:
#get minimum
np.min(stats)

0.09166967350628152

In [75]:
#get maximum
np.max(stats)

0.7992880455834485

In [76]:
#get minimum along axis
np.min(stats,axis=1)

array([0.09166967, 0.14981479])

In [77]:
np.min(stats,axis=0)

array([0.09166967, 0.38406215, 0.39098961])

In [78]:
#get maximum along axis
np.max(stats,axis=1)

array([0.539444  , 0.79928805])

In [79]:
np.max(stats,axis=0)

array([0.14981479, 0.79928805, 0.539444  ])

In [80]:
#sum
np.sum(stats)

2.355268273863616

In [81]:
np.sum(stats,axis=1)

array([1.01517583, 1.34009244])

### Reorganizing arrays

In [82]:
#reshaping
before=np.array([[1,2,3,4],[5,6,7,8]])
before.shape

(2, 4)

In [83]:
after=before.reshape(8,1)
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [84]:
after=before.reshape(2,2,2)
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [85]:
## note: the new shape you will resize into must fit the original shape
#eg-
after=before.reshape(2,2)
after

ValueError: cannot reshape array of size 8 into shape (2,2)

In [87]:
#vertically stacking vectors. note: sizes must match
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
np.vstack([v1,v2,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [89]:
#horizontally stacking vectors
h1=np.ones((2,4))
h2=np.zeros((2,2))
print(h1)
print(h2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [90]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [91]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

### Load data from file

In [92]:
np.genfromtxt('data2.txt',delimiter=',')

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [93]:
#note that the data above is cast into float data type

In [94]:
filedata=np.genfromtxt('data2.txt',delimiter=',')
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [95]:
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [96]:
filedata=filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean masking & advanced indexing

In [97]:
filedata>50  #check values >50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [98]:
filedata[filedata>50]   #grab values greater than 50

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [99]:
#the code above illustrates that index a list with a list in NumPy
#further example below
b=np.array([1,2,3,4,5,6,7,8,9])
b[[1,2,8]]

array([2, 3, 9])

In [100]:
np.any(filedata>50, axis=0) #which columns have a value greater than 50

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [101]:
np.all(filedata>50, axis=0) #check if all data in axis is greater than 50

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [102]:
np.any(filedata>50)

True

In [103]:
np.all(filedata>50, axis=1)

array([False, False, False])

In [104]:
((filedata>50)& (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [105]:
~((filedata>50)& (filedata<100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])